169Capstone/Assets/Art/3D/Character.meta, 169Capstone/Assets/Art/3D/Levels.meta, 169Capstone/Assets/Prefab/Player.prefab, 169Capstone/Assets/Prefab/Player.prefab.meta, 169Capstone/Assets/Scenes/Small Level.unity
Went into small level and created prefab of player and replaced with YBot
=> Swap player in main scene

169Capstone/Assets/Scenes/Small Level.unity
Edited the scene file to have one less merge conflict for a total of zero merge conflicts
=> Fix merge conflict

169Capstone/Assets/Art/Sprites/slime_spritesheet.png.meta, 169Capstone/Assets/Scenes/ChasesRandomGarbage.unity, 169Capstone/Assets/Scripts/Billboard.cs, 169Capstone/Assets/Scripts/Billboard.cs.meta, 169Capstone/Packages/manifest.json, 169Capstone/Packages/packages-lock.json
Made a script that points a transform toward the camera
=> Implemented billboarding script

169Capstone/Assets/Animation/Enemies/Slime/Slime.controller, 169Capstone/Assets/Animation/Enemies/Slime/SlimeAttackDuration.anim, 169Capstone/Assets/Animation/Enemies/Slime/SlimeAttackWindDown.anim, 169Capstone/Assets/Animation/Enemies/Slime/SlimeAttackWindUp.anim, 169Capstone/Assets/Animation/Enemies/Slime/SlimeIdle.anim, 169Capstone/Assets/Animation/Enemies/Slime/SlimeMove.anim, 169Capstone/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, 169Capstone/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset, 169Capstone/Assets/Scenes/Medium Level.meta
=> Slime animations but without the prefab change thing

169Capstone/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset, 169Capstone/Assets/ScriptableObjects/Enemies/Robert.asset, 169Capstone/Assets/ScriptableObjects/Enemies/Slime.asset
Added health and move speed to them
=> Slime & Rober Stats

169Capstone/Assets/Animation/Player/Sword Attack Duration.anim, 169Capstone/Assets/Animation/Player/Sword Attack Duration.anim.meta, 169Capstone/Assets/Animation/Player/Sword Wind Down.anim, 169Capstone/Assets/Animation/Player/Sword Wind Down.anim.meta, 169Capstone/Assets/Animation/Player/Sword Wind Up.anim, 169Capstone/Assets/Animation/Player/Sword Wind Up.anim.meta
We have a wind up, attack duration, and a wind down
=> Split player animations

169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/BigPit.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/HG turret.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Lazer hoard.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Low cover_.prefab
=> Greybox levels

169Capstone/Assets/Scripts/Gear/Weapon/Melee/Longsword.cs, 169Capstone/Assets/Scripts/Utilities/PropJumpBreak.cs
Woops, added props breaking when hit
=> Main hub revamp

169Capstone/Assets/Scenes/Main Hub.unity
main hub elevator has the correct string now
=> main hub elevator set to go to the right place now

169Capstone/Assets/Prefab/Models/Era 2 Coil Trap.prefab
Added a second VFX, flipped it and made it a child of the first one
=> Fixed Coil Trap VFX

169Capstone/Assets/Art/Shaders/Blue Slime.mat, 169Capstone/Assets/Art/Shaders/Blue Slime.mat.meta, 169Capstone/Assets/Art/Shaders/Slime.shadergraph, 169Capstone/Assets/Scenes/Lich Fight.unity
Changed the lich fight slime to be blue
=> Lich pools

169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Prefab/Room Parts/Wall.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/BigPit.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/HG turret.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Lazer hoard.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Rector.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Scuffed v2.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Spikes.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Spikes.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Turret v2.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Turret v2.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Pillar+Spikes.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Pillar+Spikes.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Pillar.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Pillar.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Spikes.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/1x1 Spikes.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Jump.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Let it rip.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Low cover_.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/No U 1.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Small Corner.prefab, 169Capstone/Assets/Prefab/Utilities/Generator.prefab, 169Capstone/Assets/Scenes/GenerationSetup.unity, 169Capstone/Assets/Scenes/Medium Level.meta
NEW ROOOOOMS, boots and pants and (also wall new wall prefab just dropped)
=> Added some new rooms and made wall prefab

169Capstone/Assets/Prefab/Room Prefabs/Scuffed.prefab
=> Small fix to corner room

169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Art/Shaders/Hologram.mat, 169Capstone/Assets/Art/Shaders/Hologram.mat.meta, 169Capstone/Assets/Prefab/Room Prefabs/Scuffed.prefab, 169Capstone/Assets/Prefab/Room Prefabs/SpawnRoom.prefab, 169Capstone/Assets/Scenes/Main Hub.unity, 169Capstone/Assets/Scenes/Medium Level.meta
- Added wall prefabs to spawn room
- Added wall prefabs to scuffed 1x1 room
- Tried to fix clipping issue in scuffed 1x1 room 
- Added floor edge to spawn room
=> Aesthetic changes

169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Prefab/Player.prefab, 169Capstone/Assets/Scenes/GenerationSetup.unity, 169Capstone/Assets/Scenes/GenerationSetup/Global Volume Profile.asset, 169Capstone/Assets/Scenes/GenerationSetup/Global Volume Profile.asset.meta, 169Capstone/Assets/Scenes/Main Hub.unity, 169Capstone/Assets/Scenes/Medium Level.meta
fixed input but forgot i had started post processin
=> fixed input but forgot i had started post processing

169Capstone/Assets/Prefab/UIPrefabs/DialogueManager2.0.prefab, 169Capstone/Assets/Prefab/UIPrefabs/UICanvas2.0.prefab, 169Capstone/Assets/Scenes/UI Scenes/MainMenu.unity, 169Capstone/Assets/Scripts/Utilities/DevPanel.cs
- dev panel is now collapsible
- dialogue next button doesn't do anything anymore (this is what we want)
=> dev panel tweak; dialogue bug fix

169Capstone/Assets/Art/Shaders/Slime.mat, 169Capstone/Assets/Art/Shaders/Slime.shadergraph, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Lazer hoard.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/-.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Coil 1x1.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Coil 1x1.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Jump.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Low Cover 1x1.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Low Cover 1x1.prefab.meta, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/No U 1.prefab, 169Capstone/Assets/Prefab/Utilities/Generator.prefab, 169Capstone/Assets/Scenes/GenerationSetup.unity, 169Capstone/Assets/Scenes/NicksTest.unity
=> Hallway changes

169Capstone/Assets/Animation/Player/Shooting Arrow Duration.anim, 169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Prefab/Player.prefab, 169Capstone/Assets/Prefab/Room Parts/ForceField.prefab, 169Capstone/Assets/Scenes/Medium Level.meta, 169Capstone/Assets/Scripts/Entity/Enemy/Slime.cs, 169Capstone/Assets/Scripts/Entity/Player/Animation/AnimationStateController.cs
Fixed issue with sword slash vfx appearing when on the bow
fixed issue of partials never being destroyed
=> Sword VFX fix and Partical cleanup

169Capstone/Assets/Scripts/Entity/Enemy/Robert.cs
=> I forgot robert

169Capstone/Assets/Art/Materials/Item mats/Helm of SnowStorm.mat, 169Capstone/Assets/Prefab/Gear/Helmets/Models/Helm of Snowstorms.prefab, 169Capstone/Assets/Prefab/Gear/Helmets/Models/Helm of Snowstorms.prefab.meta, 169Capstone/Assets/ScriptableObjects/Gear/EquipmentData/Helmets/HelmOfSnowstorms.asset
setup the new drop texture for helm of snowstorms
=> Hos model setup

169Capstone/Assets/Prefab/Room Prefabs/SpawnRoom.prefab, 169Capstone/Assets/Prefab/Utilities/CaptainsLog.prefab
=> Captains log arrow

169Capstone/Assets/Prefab/Room Prefabs/Pest Controll Spicey.prefab, 169Capstone/Assets/Scenes/GenerationSetup.unity, 169Capstone/Assets/Scripts/Utilities/EncounterRoomClose.cs
Might re-visit the red light latter
=> Changed how the lighting in bryn's fight works

169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Rector.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Scuffed v2.prefab
=> moved in enemy spawns to stop soft locks

169Capstone/Assets/Scenes/Lich Fight.unity
=> moved some walls that were placed incorrectly

169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Prefab/Models/Era 2 Turret.prefab, 169Capstone/Assets/Prefab/Room Parts/SlimePlane.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Scuffed v2.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Pest Controll Spicey.prefab, 169Capstone/Assets/Scenes/Medium Level.meta
put in numbers for the turret and added a light
added sprites so that the beetle boss room shows up on the mini map
=> Turret changes and boss room mini map stuff

169Capstone/Assets/Art/3D/particals.meta, 169Capstone/Assets/Prefab/Room Parts/BlackoutWalls.prefab, 169Capstone/Assets/Prefab/Room Prefabs/EncounterRooms/Lazer hoard.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/-.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/Jump.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Hallways/No U 1.prefab, 169Capstone/Assets/Scenes/Medium Level.meta
=> Changed rooms so they dont hide the cool new background

169Capstone/Assets/Prefab/Room Prefabs/Pest Controll Spicey.prefab
=> Exterminated the sticky wall

169Capstone/Assets/Scenes/EpilogueScene.unity
=> Murdered Orby

169Capstone/Assets/Prefab/Enemies/Debris.prefab, 169Capstone/Assets/Prefab/Enemies/Meteor Hit Point.prefab.meta, 169Capstone/Assets/Prefab/Enemies/Meteor.prefab, 169Capstone/Assets/Prefab/NPCs/Bryn.prefab, 169Capstone/Assets/Prefab/NPCs/Doctor.prefab, 169Capstone/Assets/Prefab/NPCs/Rhian.prefab, 169Capstone/Assets/Prefab/Particles/PropExplotion.prefab, 169Capstone/Assets/Prefab/Particles/PropExplotion.prefab.meta, 169Capstone/Assets/Prefab/Room Parts/Scifi Barrel.prefab, 169Capstone/Assets/Prefab/Room Parts/ScifiCrate.prefab, 169Capstone/Assets/Prefab/Room Parts/ScifiEnergyCell.prefab, 169Capstone/Assets/Prefab/Room Parts/ScifiEngine.prefab, 169Capstone/Assets/Prefab/Room Parts/ScifiEngine.prefab.meta, 169Capstone/Assets/Prefab/Room Parts/ScifiLongBox.prefab, 169Capstone/Assets/Prefab/Room Prefabs/BrynShop.prefab, 169Capstone/Assets/Prefab/Room Prefabs/DoctorShop.prefab, 169Capstone/Assets/Prefab/Room Prefabs/Pest Controll Spicey.prefab, 169Capstone/Assets/Prefab/Room Prefabs/RhianShop.prefab, 169Capstone/Assets/Scenes/Medium Level.meta, 169Capstone/Assets/Scripts/Traps/DisableTrap.cs, 169Capstone/Assets/Scripts/Utilities/PropJumpBreak.cs
=> Prop destroy particle

169Capstone/Assets/Prefab/Enemies/Debris.prefab, 169Capstone/Assets/Prefab/Enemies/Meteor.prefab, 169Capstone/Assets/Prefab/Particles/MeteorExplotion.prefab, 169Capstone/Assets/Prefab/Particles/MeteorExplotion.prefab.meta, 169Capstone/Assets/Scripts/Entity/Enemy/Beetle/FallingDebris.cs, 169Capstone/Assets/Scripts/Entity/Enemy/Lich/FallingMeteor.cs
=> Boss falling stuff break partical
